import React from 'react'

const TermConditionData = () => {
    return (
      <div className="container py-4" style={{marginTop:"70px"}}>
      <div className="row">
        <div className="col-md-12">
          <h2 className="text-center" style={{"font-weight":"700","color":"#78006E"}}>Terms &amp; Conditions <i className="fa-solid fa-file-contract" style={{"color":"#78006E"}} /></h2>
          <hr />
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>1.General Terms: <span className="text-danger">*</span></h6>
            <ul>
              <li style={{"font-weight":"600"}}>By accessing and placing an order with Renomadic (registered under
                SNG India), confirm that you are in agreement with and bound by the terms of service
                contained in the Terms &amp; Conditions outlined below. These terms apply to the entire website
                and any email or other type of communication between you and Renomadic.</li>
              <li style={{"font-weight":"600"}}>Under no circumstances shall Renomadic team be liable for any
                direct, indirect, special, incidental or consequential damages, including, but not limited
                to, loss of data or profit, arising out of the use, or the inability to use, the materials
                on this site, even if Renomadic team or an authorized representative has been advised of the
                possibility of such damages. If your use of materials from this site results in the need for
                servicing, repair or correction of equipment or data, you assume any costs thereof.</li>
              <li style={{"font-weight":"600"}}>Renomadic will not be responsible for any outcome that may occur
                during the course of usage of our resources. We reserve the resource rights to change prices
                and revise the usage policy at any moment.</li>
            </ul>
          </div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>2.License: <span className="text-danger">*</span>
            </h6>
            <ul>
              <li style={{"font-weight":"600"}}>Renomadic grants you a revocable, non-exclusive, non-transferable,
                limited license to download, install and use the website strictly in accordance with the
                terms of this Agreement.</li>
              <li style={{"font-weight":"600"}}>These Terms &amp; Conditions are a contract between you and Renomadic
                (referred to in these Terms &amp; Conditions as “Renomadic”, “us”, “we” or “our”), the provider
                of the Renomadic website and the services accessible from the Renomadic website (which are
                collectively referred to in these Terms &amp; Conditions as the “Renomadic Service”).</li>
              <li style={{"font-weight":"600"}}>You are agreeing to be bound by these Terms &amp; Conditions. If you
                do not agree to these Terms &amp; Conditions, please do not use the Renomadic Service. In these
                Terms &amp; Conditions, “you” refers both to you as an individual and to the entity you
                represent. If you violate any of these Terms &amp; Conditions, we reserve the right to cancel
                your account or block access to your account without notice.</li>
            </ul>
          </div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>3.Definitions and key terms: <span className="text-danger">*</span></h6>
            <ul>
              <li style={{"font-weight":"600"}}>To help explain things as clearly as possible in this Terms &amp;
                Conditions, every time any of these terms are referenced, are strictly defined as:</li>
              <li style={{"font-weight":"600"}}>Cookie: small amount of data generated by a website and saved by
                your web browser. It is used to identify your browser, provide analytics, remember
                information about you such as your language preference or login information.</li>
              <li style={{"font-weight":"600"}}>Company: when this policy mentions “Company,” “we,” “us,” or
                “our,” it refers to Renomadic, B-48, F/F, Dashrathpuri, New Delhi, India that is responsible
                for your information under this Terms &amp; Conditions</li>
              <li style={{"font-weight":"600"}}>Country: where Renomadic or the owners/founders of Renomadic are
                based, in this case is United Arab Emirates</li>
              <li style={{"font-weight":"600"}}>Device: any internet connected device such as a phone, tablet,
                computer or any other device that can be used to visit Renomadic and use the services.</li>
              <li style={{"font-weight":"600"}}> Service: refers to the service provided by Renomadic as described
                in the relative terms (if available) and on this platform.</li>
              <li style={{"font-weight":"600"}}>Third-party service: refers to advertisers, contest sponsors,
                promotional and marketing partners, and others who provide our content or whose products or
                services we think may interest you.</li>
              <li style={{"font-weight":"600"}}> Website: Renomadic's site, which can be accessed via this URL: <a href>www.Renomadic.com</a> </li>
              <li style={{"font-weight":"600"}}>You: a person or entity that is registered with Renomadic to use
                the Services.</li>
            </ul>
          </div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>4.Restrictions: <span className="text-danger">*</span></h6>
            <p style={{"font-size":"14px","font-weight":"700"}} >You agree not to, and you will not permit others to:
            </p>
            <ul>
              <li style={{"font-weight":"600"}}>License, sell, rent, lease, assign, distribute, transmit, host,
                outsource, disclose or otherwise commercially exploit the website or make the platform
                available to any third party.</li>
              <li style={{"font-weight":"600"}}>Remove, alter or obscure any proprietary notice (including any
                notice of copyright or trademark) of Renomadic or its affiliates, partners, suppliers or the
                licensors of the website.</li>
              <li style={{"font-weight":"600"}}>Company: when this policy mentions “Company,” “we,” “us,” or
                “our,” it refers to Renomadic, B-48, F/F, Dashrathpuri, New Delhi, India that is responsible
                for your information under this Terms &amp; Conditions</li>
            </ul></div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>5.Return and Refund Policy: <span className="text-danger">*</span></h6>
            <ul>
              <li style={{"font-weight":"600"}}>Thanks for shopping at Renomadic. We appreciate the fact that you
                like to buy the stuff we build. We also want to make sure you have a rewarding experience
                while you're exploring, evaluating, and purchasing our products.</li>
              <li style={{"font-weight":"600"}}>As with any shopping experience, there are terms and conditions
                that apply to transactions at Renomadic. We'll be as brief as our attorneys will allow. The
                main thing to remember is that by placing an order or making a purchase at Renomadic, you
                agree to the terms along with Renomadic's Privacy Policy..</li>
              <li style={{"font-weight":"600"}}>If, for any reason, you are not completely satisfied with any good
                or service that we provide, don't hesitate to contact us and we will discuss any of the
                issues you are going through with our product.</li>
            </ul></div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>6.Cancellation Policy: <span className="text-danger">*</span></h6>
            <ul>
              <li style={{"font-weight":"600"}}>Please note that tickets purchased through our platform are
                non-refundable. We appreciate your understanding in this matter.</li>
            </ul></div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>7.Your Suggestions: <span className="text-danger">*</span></h6>
            <ul>
              <li style={{"font-weight":"600"}}>Any feedback, comments, ideas, improvements or suggestions
                (collectively, "Suggestions") shall be provided by you to Renomadic with respect to the
                website remain the sole and exclusive property of Renomadic.</li>
              <li style={{"font-weight":"600"}}>Renomadic shall be free to use, copy, modify, publish, or
                redistribute the Suggestions for any purpose and in any way without any credit or any
                compensation to you.</li>
            </ul></div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>8.Your Consent:<span className="text-danger">*</span></h6>
            <ul>
              <li style={{"font-weight":"600"}}> We've updated our Terms &amp; Conditions to provide you with complete
                transparency into what is being set when you visit our site and how it's being used. By
                using our website, registering an account, or making a purchase, you hereby consent to our
                Terms &amp; Conditions.</li>
            </ul></div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>9.Links to Other Websites:<span className="text-danger">*</span></h6>
            <ul>
              <li style={{"font-weight":"600"}}> These Terms &amp; Conditions apply only to the Services. The Services
                may contain links to other websites not operated or controlled by Renomadic. We are not
                responsible for the content, accuracy or opinions expressed in such websites, and such
                websites are not investigated, monitored or checked for accuracy or completeness by us.
                Please remember that when you use a link to go from the Services to another website, our
                Terms &amp; Conditions are no longer in effect. Your browsing and interaction on any other
                website, including those that have a link on our platform, is subject to that website’s own
                rules and policies. Such third parties may use their own cookies or other methods to collect
                information about you.</li>
            </ul></div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>10.Cookies:<span className="text-danger">*</span>
            </h6>
            <ul>
              <li style={{"font-weight":"600"}}>Renomadic uses "Cookies" to identify the areas of our website that
                you have visited. A cookie is a small piece of data stored on your computer or mobile device
                by your web browser. We use cookies to enhance the performance and functionality of our
                website but are non-essential to their use. However, without these cookies, certain
                functionality like videos may become unavailable or you would be required to enter your
                login details every time you visit the website as we would not be able to remember that you
                had logged in previously. Most web browsers can be set to disable the use of cookies.
                However, if you disable cookies, you may not be able to access functionality on our website
                correctly or at all. We never place Personally Identifiable Information in Cookies.</li>
            </ul></div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>11.Changes To Our Terms &amp; Conditions:<span className="text-danger">*</span></h6>
            <ul>
              <li style={{"font-weight":"600"}}>You acknowledge and agree that we may stop (permanently or
                temporarily) providing the Service (or any features within the Service) to you or to users
                generally at our sole discretion, without prior notice to you. You may stop using the
                Service at any time. You do not need to specifically inform us when you stop using the
                Service.</li>
              <li style={{"font-weight":"600"}}>We may revise these Terms &amp; Conditions from time to time. The
                changes will not be retroactive, and the most current version of the Terms &amp; Conditions,
                which will always be at Renomadic website, will govern our relationship with you. We will
                try to notify you of material revisions, for example via a service notification or an email
                to the email associated with your account. By continuing to access or use the Services after
                those revisions become effective, you agree to be bound by the revised Terms &amp; Conditions.
              </li>
            </ul></div>
          <div>
            <h6 className style={{"font-weight":"700","color":"#78006E"}}>12.Contact Us:<span className="text-danger">*</span>
            </h6>
            <ul>
              <li style={{"font-weight":"600"}}>If you have any questions about these Terms &amp; Conditions, please
                contact us at: support@renomadic.com</li>
            </ul></div>
        </div>
      </div>
    </div>
      )
}

export default TermConditionData
