import React from 'react'

const ContactUsData = () => {
    return (
        <div style={{marginTop:"110px", marginBottom:"70px"}}>
          Privacy Policy
    1.General Items:
    By accessing and placing an order with Renomadic (registered under SNG India), confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Renomadic.
    
    Under no circumstances shall Renomadic team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Renomadic team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
    
    Renomadic will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the resource rights to change prices and revise the usage policy at any moment.
    
    2.License :
    Renomadic grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.
    
    These Terms & Conditions are a contract between you and Renomadic (referred to in these Terms & Conditions as “Renomadic”, “us”, “we” or “our”), the provider of the Renomadic website and the services accessible from the Renomadic website (which are collectively referred to in these Terms & Conditions as the “Renomadic Service”).
    
    You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Renomadic Service. In these Terms & Conditions, “you” refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.
    
    Definitions and key terms:
    To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:
    
    Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
    
    Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Renomadic, B-48, F/F, Dashrathpuri, New Delhi, India that is responsible for your information under this Terms & Conditions.
    
    Country: where Renomadic or the owners/founders of Renomadic are based, in this case is United Arab Emirates
    
    Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Renomadic and use the services.
    
    Service: refers to the service provided by Renomadic as described in the relative terms (if available) and on this platform.
    
    Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
    
    Website: Renomadic's site, which can be accessed via this URL:
    
    www.Renomadic.com
    
    You: a person or entity that is registered with Renomadic to use the Services.
    Restrictions:
    You agree not to, and you will not permit others to:
    License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.
    
    Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.
    
    Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Renomadic or its affiliates, partners, suppliers or the licensors of the website.
    
    Return and Refund Policy:
    Thanks for shopping at Renomadic. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products.
    
    As with any shopping experience, there are terms and conditions that apply to transactions at Renomadic. We'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Renomadic, you agree to the terms along with Renomadic's Privacy Policy.
    
    If, for any reason, you are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.
    Cancellation Policy:
    Please note that tickets purchased through our platform are non-refundable. We appreciate your understanding in this matter.
    Your Suggestions:
    Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") shall be provided by you to Renomadic with respect to the website remain the sole and exclusive property of Renomadic.
    
    Renomadic shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
    Your Consent:
    We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.
    
    Links to Other Websites:
    These Terms & Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by Renomadic. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
    Cookies:
    Renomadic uses "Cookies" to identify the areas of our website that you have visited. A cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of cookies. However, if you disable cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
    Changes To Our Terms & Conditions:
    You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service.
    
    We may revise these Terms & Conditions from time to time. The changes will not be retroactive, and the most current version of the Terms & Conditions, which will always be at Renomadic website, will govern our relationship with you. We will try to notify you of material revisions, for example via a service notification or an email to the email associated with your account. By continuing to access or use the Services after those revisions become effective, you agree to be bound by the revised Terms & Conditions.
    Contact Us:
    If you have any questions about these Terms & Conditions, please contact us at: support@renomadic.com
    
    
    
    Cancellation:
    Renomadic understands that plans may change. If you need to cancel your booking, simply notify us within the specified cancellation period for a hassle-free process.
    
    Cancellation periods may vary depending on the activity booked. Please refer to your booking confirmation for details
    
    To cancel, contact our customer support team or follow the cancellation instructions provided in your booking confirmation.
    Refund:
    Renomadic offers refunds for eligible cancellations within the designated cancellation period.
    
    Refund eligibility and processing times may vary depending on the activity and provider. Please refer to your booking confirmation for specific refund policies.
    
    Refunds will be issued to the original payment method used for booking.
    
    Processing fees or non-refundable portions may apply as per the activity provider's terms and conditions.
    
    For any questions or assistance regarding refunds, feel free to reach out to our customer support team.
    
    Note:
    Non-refundable tickets or activities with special cancellation policies will be clearly indicated at the time of booking.
    
    Renomadic reserves the right to modify or update the cancellation and refund policy as necessary. Any changes will be communicated promptly to customers.
        </div>
      )
}

export default ContactUsData
